The code for ILM is included in this repository, but the original and the setup instructions can be found [here](https://github.com/chrisdonahue/ilm). Before we can train the model, the compound dataset that we've created in the previous notebook needs be preprocessed: 

In [2]:
import nltk 
nltk.download('punkt')  

[nltk_data] Downloading package punkt to /home/onyxia/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
!sh ./ilm/create_compound_dataset.sh

  2%|▊                                    | 1753/79146 [00:07<03:20, 386.63it/s]/Users/joanna/Documents/mva/S2/NLP/necessity-sufficiency/ilm/ilm/tokenize_util.py:182: UserWarning: Encountered empty token
  warnings.warn('Encountered empty token')
100%|████████████████████████████████████| 79146/79146 [04:45<00:00, 277.19it/s]
Processed 79146 documents and created 15.640310312586864 examples per document (expected 16)
Errors which caused retries:
* (451890 retries) Issue with example: Mask is not unique
* (297984 retries) Mask function exception: Tokenizer produced token not found in string
Mask rate (characters): 0.2002
100%|██████████████████████████████████████| 4168/4168 [00:13<00:00, 302.23it/s]
Processed 4168 documents and created 15.692898272552783 examples per document (expected 16)
Errors which caused retries:
* (22460 retries) Issue with example: Mask is not unique
* (13056 retries) Mask function exception: Tokenizer produced token not found in string
Mask rate (characters): 0

Then, we can run the training:

In [ ]:
%%bash
DATASET=compound_dataset
TRAIN_DIR=../Models/ILM
EXAMPLES_DIR=Data/data_ilm/${DATASET}
python ilm/train_ilm.py \
	experiment_${DATASET} \
	${TRAIN_DIR} \
	${EXAMPLES_DIR} \
	--train_examples_tag train \
	--eval_examples_tag valid \
	--train_num_epochs 4 \
	--eval_max_num_examples 512

Random seed 42
{50257: '<|startofinfill|>', 50258: '<|endofinfill|>', 50259: '<|infill_document|>', 50260: '<|infill_paragraph|>', 50261: '<|infill_sentence|>', 50262: '<|infill_ngram|>', 50263: '<|infill_word|>'}
Loading training data


100%|██████████| 79146/79146 [02:26<00:00, 540.25it/s]


[[1 1 1 ... 0 0 0]
 [2 1 1 ... 0 0 0]
 [2 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 5 4 4]
 [2 2 1 ... 5 4 5]
 [1 1 1 ... 0 0 0]]
{<TargetType.PAD: 0>: np.int64(216243254), <TargetType.CONTEXT: 1>: np.int64(63848439), <TargetType.CONTEXT_SPECIAL: 2>: np.int64(6305423), <TargetType.CONTEXT_INFILL_SEP: 3>: np.int64(1147304), <TargetType.INFILL: 4>: np.int64(13167501), <TargetType.INFILL_SPECIAL: 5>: np.int64(4966671)}
Mask rate (tokens): 0.1710
79146 documents, 1194057 examples
(1194057, 256) uint16 (1194057, 256) uint8
Loading eval data


100%|██████████| 4168/4168 [00:08<00:00, 513.34it/s]


{<TargetType.PAD: 0>: np.int64(97133), <TargetType.CONTEXT: 1>: np.int64(24278), <TargetType.CONTEXT_SPECIAL: 2>: np.int64(2399), <TargetType.CONTEXT_INFILL_SEP: 3>: np.int64(487), <TargetType.INFILL: 4>: np.int64(4984), <TargetType.INFILL_SPECIAL: 5>: np.int64(1791)}
Mask rate (tokens): 0.1703
4168 documents, 512 examples
(512, 256) uint16 (512, 256) uint8
Maximum number of training steps: 13191.0
Creating datasets
Initializing model...
from pretrained checkpoint


The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
/opt/conda/lib/python3.12/site-packages/transformers/optimization.py:640: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Training
--------------------------------------------------------------------------------
(Step 0) Eval
eval_context_count: 23841
eval_context_loss: 5.049341289765392
eval_infill_count: 6775
eval_infill_loss: 8.464201763969506
eval_infill_textonly_count: 4984
eval_infill_textonly_loss: 6.092544096526518
eval_time: 11.160985469818115
Saving
Estimated disk space required: 621.98 MB
None
Model and related data saved successfully to ../Models/ILM/step_0
--------------------------------------------------------------------------------
(Step 0) Summary
5.455732822418213
8.424469947814941
----------------------------------------
[np.int64(855), np.int64(11274), np.int64(50263), np.int64(1222), np.int64(23748), np.int64(855), np.int64(275), np.int64(615), np.int64(291), np.int64(16), np.int64(50263), np.int64(50263), np.int64(2836), np.int64(2443), np.int64(11), np.int64(1842), np.int64(262), np.int64(10559), np.int64(290), np.int64(511), np.int64(13888), np.int64(0), np.int64(220), np.int64(88